import Head from 'next/head';
import Layout from '../components/layout/Layout';

export default function Reports() {
  const sampleReports = [
    {
      title: "NFT Smart Contract Analysis",
      description: "Comprehensive multi-AI security analysis of an NFT contract using 6 AI models",
      type: "Premium Analysis",
      findings: "10 security findings",
      score: "88/100",
      date: "June 8, 2025",
      icon: "🎨",
      reportUrl: "/sample-report.html",
      highlights: [
        "6 AI Specialists Analysis",
        "Gas Optimization Opportunities", 
        "Code Quality Assessment",
        "Executive Summary"
      ]
    },
    {
      title: "DeFi Token Contract",
      description: "Security analysis of a DeFi token with advanced tokenomics",
      type: "Premium Analysis",
      findings: "5 security findings",
      score: "92/100",
      date: "Coming Soon",
      icon: "🪙",
      reportUrl: "#",
      highlights: [
        "DeFi Protocol Analysis",
        "Economic Attack Vectors",
        "Liquidity Pool Security",
        "Governance Analysis"
      ]
    },
    {
      title: "DAO Governance Contract", 
      description: "Analysis of a decentralized autonomous organization governance system",
      type: "Premium Analysis",
      findings: "8 security findings",
      score: "85/100",
      date: "Coming Soon",
      icon: "🏛️",
      reportUrl: "#",
      highlights: [
        "Voting Mechanism Security",
        "Proposal System Analysis", 
        "Access Control Review",
        "Economic Incentives"
      ]
    }
  ];

  const reportFeatures = [
    {
      icon: "🤖",
      title: "Multi-AI Analysis",
      description: "6+ specialized AI models analyze your contract in parallel"
    },
    {
      icon: "📊",
      title: "Executive Dashboard",
      description: "High-level security scores and risk assessment for stakeholders"
    },
    {
      icon: "🛡️",
      title: "Security Findings",
      description: "Detailed vulnerability analysis with severity ratings and recommendations"
    },
    {
      icon: "⚡",
      title: "Gas Optimization",
      description: "Specific recommendations to reduce deployment and execution costs"
    },
    {
      icon: "✨",
      title: "Code Quality",
      description: "Best practices review and maintainability assessment"
    },
    {
      icon: "📋",
      title: "Professional Reports",
      description: "Export-ready reports in multiple formats (HTML, PDF, JSON)"
    }
  ];

  return (
    <Layout>
      <Head>
        <title>Sample Reports - DeFi Watchdog</title>
        <meta name="description" content="View sample security analysis reports generated by DeFi Watchdog's multi-AI analysis platform." />
      </Head>

      <div className="bg-gradient-to-b from-gray-50 to-white">
        {/* Hero Section */}
        <section className="pt-32 pb-20">
          <div className="container mx-auto px-6">
            <div className="max-w-4xl mx-auto text-center">
              <div className="inline-flex items-center py-2 px-4 rounded-full bg-purple-100 text-purple-700 text-sm font-medium mb-6">
                <span className="mr-2">📊</span>
                Sample Reports
              </div>
              
              <h1 className="text-4xl md:text-6xl font-bold text-gray-900 mb-6">
                Professional Security
                <span className="bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent"> Reports</span>
              </h1>
              
              <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
                Explore real examples of our comprehensive security analysis reports. 
                See how our 9-tool platform identifies vulnerabilities and provides actionable insights.
              </p>
            </div>
          </div>
        </section>

        {/* Sample Reports Grid */}
        <section className="py-20 bg-white">
          <div className="container mx-auto px-6">
            <div className="max-w-6xl mx-auto">
              <h2 className="text-3xl md:text-4xl font-bold text-center mb-16">
                Sample Analysis Reports
              </h2>
              
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                {sampleReports.map((report, index) => (
                  <div key={index} className="bg-white rounded-2xl shadow-xl border border-gray-200 overflow-hidden hover:shadow-2xl transition-shadow duration-300">
                    <div className="p-8">
                      <div className="text-4xl mb-4 text-center">{report.icon}</div>
                      <h3 className="text-xl font-bold text-gray-900 mb-3">{report.title}</h3>
                      <p className="text-gray-600 mb-4">{report.description}</p>
                      
                      <div className="space-y-3 mb-6">
                        <div className="flex justify-between items-center">
                          <span className="text-sm text-gray-500">Type:</span>
                          <span className="text-sm font-medium text-purple-600">{report.type}</span>
                        </div>
                        <div className="flex justify-between items-center">
                          <span className="text-sm text-gray-500">Findings:</span>
                          <span className="text-sm font-medium">{report.findings}</span>
                        </div>
                        <div className="flex justify-between items-center">
                          <span className="text-sm text-gray-500">Score:</span>
                          <span className="text-sm font-bold text-green-600">{report.score}</span>
                        </div>
                        <div className="flex justify-between items-center">
                          <span className="text-sm text-gray-500">Date:</span>
                          <span className="text-sm">{report.date}</span>
                        </div>
                      </div>
                      
                      <div className="mb-6">
                        <h4 className="text-sm font-semibold text-gray-700 mb-2">Report Highlights:</h4>
                        <div className="space-y-1">
                          {report.highlights.map((highlight, idx) => (
                            <div key={idx} className="flex items-center text-sm text-gray-600">
                              <span className="w-1.5 h-1.5 bg-purple-400 rounded-full mr-2"></span>
                              {highlight}
                            </div>
                          ))}
                        </div>
                      </div>
                      
                      <a
                        href={report.reportUrl}
                        target={report.reportUrl !== "#" ? "_blank" : "_self"}
                        rel="noopener noreferrer"
                        className={`w-full py-3 px-6 rounded-lg font-semibold text-center block transition-colors ${
                          report.reportUrl !== "#"
                            ? "bg-gradient-to-r from-purple-600 to-blue-600 text-white hover:from-purple-700 hover:to-blue-700"
                            : "bg-gray-100 text-gray-400 cursor-not-allowed"
                        }`}
                      >
                        {report.reportUrl !== "#" ? "View Report" : "Coming Soon"}
                      </a>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* Report Features */}
        <section className="py-20 bg-gray-50">
          <div className="container mx-auto px-6">
            <div className="max-w-6xl mx-auto">
              <div className="text-center mb-16">
                <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-6">
                  What's Included in Our Reports
                </h2>
                <p className="text-lg text-gray-600 max-w-3xl mx-auto">
                  Every DeFi Watchdog report provides comprehensive analysis and actionable insights 
                  for developers, auditors, and stakeholders.
                </p>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                {reportFeatures.map((feature, index) => (
                  <div key={index} className="bg-white rounded-xl p-6 shadow-lg hover:shadow-xl transition-shadow">
                    <div className="text-3xl mb-4">{feature.icon}</div>
                    <h3 className="text-lg font-semibold text-gray-900 mb-3">{feature.title}</h3>
                    <p className="text-gray-600">{feature.description}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* Report Formats */}
        <section className="py-20 bg-white">
          <div className="container mx-auto px-6">
            <div className="max-w-4xl mx-auto">
              <div className="text-center mb-16">
                <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-6">
                  Multiple Report Formats
                </h2>
                <p className="text-lg text-gray-600">
                  Get your analysis results in the format that works best for your workflow.
                </p>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
                <div className="text-center p-6 bg-gray-50 rounded-xl">
                  <div className="text-3xl mb-3">🌐</div>
                  <h4 className="font-semibold mb-2">HTML</h4>
                  <p className="text-sm text-gray-600">Interactive web reports with detailed analysis</p>
                </div>
                <div className="text-center p-6 bg-gray-50 rounded-xl">
                  <div className="text-3xl mb-3">📄</div>
                  <h4 className="font-semibold mb-2">PDF</h4>
                  <p className="text-sm text-gray-600">Professional documents for presentations</p>
                </div>
                <div className="text-center p-6 bg-gray-50 rounded-xl">
                  <div className="text-3xl mb-3">📊</div>
                  <h4 className="font-semibold mb-2">JSON</h4>
                  <p className="text-sm text-gray-600">Machine-readable data for integrations</p>
                </div>
                <div className="text-center p-6 bg-gray-50 rounded-xl">
                  <div className="text-3xl mb-3">📋</div>
                  <h4 className="font-semibold mb-2">CSV</h4>
                  <p className="text-sm text-gray-600">Spreadsheet format for data analysis</p>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="py-20 bg-gradient-to-r from-purple-600 to-blue-600 text-white">
          <div className="container mx-auto px-6 text-center">
            <h2 className="text-3xl md:text-4xl font-bold mb-6">
              Ready to Analyze Your Contract?
            </h2>
            <p className="text-xl mb-8 max-w-2xl mx-auto opacity-90">
              Get the same comprehensive analysis for your smart contracts. 
              Start with our free tier or upgrade to premium for advanced features.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <a
                href="/audit"
                className="bg-white text-purple-600 px-8 py-3 rounded-lg font-semibold hover:bg-gray-100 transition-colors"
              >
                Start Free Analysis
              </a>
              <a
                href="/audit-pro"
                className="border-2 border-white text-white px-8 py-3 rounded-lg font-semibold hover:bg-white hover:text-purple-600 transition-colors"
              >
                Try Premium Analysis
              </a>
            </div>
          </div>
        </section>
      </div>
    </Layout>
  );
}
